CFLAGS = -fno-pic -static -fno-builtin -fno-strict-aliasing -O2 -Wall -MD -ggdb -m32 -Werror -fno-omit-frame-pointer
CFLAGS += $(shell $(CC) -fno-stack-protector -E -x c /dev/null >/dev/null 2>&1 && echo -fno-stack-protector)

CC = gcc

boot.bin : boot.elf
	objcopy -O binary boot.elf boot.bin


boot.elf: boot1.o
	ld -Ttext 0x0 -e start -melf_i386 boot1.o -o boot.elf

boot1.o: boot1.S
	$(CC) $(CFLAGS) -fno-pic -O -nostdinc -I. -c boot1.S


clean:
	rm -f boot1.o boot.bin boot.elf boot1.d
